# Generated by Django 2.0.3 on 2018-07-31 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=32)),
                ('send_counter', models.PositiveIntegerField(default=0)),
                ('last_send', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_counter', models.PositiveIntegerField(default=0)),
                ('last_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
