# Generated by Django 2.0.8 on 2018-12-30 15:29

from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command
import django.db.models.deletion

def populate_major_intake(*_):
    try:
        call_command('datautil', 'seedmajor')
    except Exception as e:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_update_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('shorten', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True)),
                ('start_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Start Year')),
                ('degree', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bachelor'), (3, 'Master')], null=True, verbose_name='Degree')),
            ],
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intake')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.AlterUniqueTogether(
            name='usermajor',
            unique_together={('user', 'major', 'intake')},
        ),
        migrations.RunPython(
            populate_major_intake,
        ),
    ]
