# Generated by Django 2.0.3 on 2018-05-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180512_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': ()},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
