const COUNTRY_LIST_REQUEST = 'COUNTRY_LIST_REQUEST';
const COUNTRY_LIST_REQUEST_SUCCESS = 'COUNTRY_LIST_REQUEST_SUCCESS';
const COUNTRY_LIST_REQUEST_PENDING = 'COUNTRY_LIST_REQUEST_PENDING';
const COUNTRY_LIST_REQUEST_FAILED = 'COUNTRY_LIST_REQUEST_FAILED';

export const COUNTRY_ACTIONS = {
    COUNTRY_LIST_REQUEST,
    COUNTRY_LIST_REQUEST_SUCCESS,
    COUNTRY_LIST_REQUEST_PENDING,
    COUNTRY_LIST_REQUEST_FAILED,
};

const CITY_LIST_BY_COUNTRY_REQUEST = 'CITY_LIST_BY_COUNTRY_REQUEST';
const CITY_LIST_BY_COUNTRY_REQUEST_SUCCESS = 'CITY_LIST_BY_COUNTRY_REQUEST_SUCCESS';
const CITY_LIST_BY_COUNTRY_REQUEST_PENDING = 'CITY_LIST_BY_COUNTRY_REQUEST_PENDING';
const CITY_LIST_BY_COUNTRY_REQUEST_FAILED = 'CITY_LIST_BY_COUNTRY_REQUEST_FAILED';

export const CITY_ACTIONS = {
    CITY_LIST_BY_COUNTRY_REQUEST,
    CITY_LIST_BY_COUNTRY_REQUEST_SUCCESS,
    CITY_LIST_BY_COUNTRY_REQUEST_PENDING,
    CITY_LIST_BY_COUNTRY_REQUEST_FAILED,
};
