
const MAJOR_REQUEST_LIST = 'MAJOR_REQUEST_LIST';
const MAJOR_REQUEST_LIST_SUCCESS = 'MAJOR_REQUEST_LIST_SUCCESS';
const MAJOR_REQUEST_LIST_FAILED = 'MAJOR_REQUEST_LIST_FAILED';
const MAJOR_REQUEST_LIST_PENDING = 'MAJOR_REQUEST_LIST_PENDING';

export const MAJOR_LIST_ACTIONS = {
    MAJOR_REQUEST_LIST,
    MAJOR_REQUEST_LIST_SUCCESS,
    MAJOR_REQUEST_LIST_FAILED,
    MAJOR_REQUEST_LIST_PENDING,
};
