const MEMBER_DETAIL_REQUEST = 'MEMBER_DETAIL_REQUEST';
const MEMBER_DETAIL_REQUEST_SUCCESS = 'MEMBER_DETAIL_REQUEST_SUCCESS';
const MEMBER_DETAIL_REQUEST_PENDING = 'MEMBER_DETAIL_REQUEST_PENDING';
const MEMBER_DETAIL_REQUEST_FAILED = 'MEMBER_DETAIL_REQUEST_FAILED';

export const MEMBER_DETAIL_ACTIONS = {
    MEMBER_DETAIL_REQUEST,
    MEMBER_DETAIL_REQUEST_SUCCESS,
    MEMBER_DETAIL_REQUEST_PENDING,
    MEMBER_DETAIL_REQUEST_FAILED,
};

const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST';
const MEMBER_LIST_REQUEST_CHANGE_PAGE = 'MEMBER_LIST_REQUEST_CHANGE_PAGE';
const MEMBER_LIST_REQUEST_SUCCESS = 'MEMBER_LIST_REQUEST_SUCCESS';
const MEMBER_LIST_REQUEST_PENDING = 'MEMBER_LIST_REQUEST_PENDING';
const MEMBER_LIST_REQUEST_FAILED = 'MEMBER_LIST_REQUEST_FAILED';

export const MEMBER_LIST_ACTIONS = {
    MEMBER_LIST_REQUEST,
    MEMBER_LIST_REQUEST_FAILED,
    MEMBER_LIST_REQUEST_PENDING,
    MEMBER_LIST_REQUEST_SUCCESS,
    MEMBER_LIST_REQUEST_CHANGE_PAGE,
};
