const LOGIN_PENDING = 'LOGIN_PENDING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_ACTIONS = {
    LOGIN_PENDING,
    LOGIN_SUCCESS,
};

const PROFILE_REQUEST_SUCCESS = 'PROFILE_REQUEST_SUCCESS';
const PROFILE_REQUEST_PENDING = 'PROFILE_REQUEST_PENDING';

export const PROFILE_ACTIONS = {
    PROFILE_REQUEST_SUCCESS,
    PROFILE_REQUEST_PENDING,
};

const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
const REGISTER_REQUEST_PENDING = 'REGISTER_REQUEST_PENDING';

export const REGISTER_ACTIONS = {
    REGISTER_REQUEST_PENDING,
    REGISTER_REQUEST_SUCCESS,
};
