# Generated by Django 2.0.3 on 2018-08-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Field')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Job Description')),
                ('requirement', models.TextField(blank=True, max_length=255, null=True, verbose_name='Job Requirement')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salary')),
                ('benefit', models.TextField(blank=True, max_length=255, null=True, verbose_name='Benefits')),
                ('apply_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resume Application To')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('question_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='For More Information')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Posted')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Post scheduled time')),
                ('facebook_post_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Post ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Field Name')),
                ('slug', models.SlugField()),
                ('file_img_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field', to='job.JobField', verbose_name='Job Field'),
        ),
    ]
