# Generated by Django 2.0.3 on 2018-05-19 14:44

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180512_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (3, 'Female'), (5, 'Undefined')], default=5, verbose_name='Gender')),
                ('major_intake', models.CharField(default='', max_length=255, verbose_name='Major - Intake')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, validators=[core.validators.validate_phone_number], verbose_name='Phone Number')),
                ('state', models.CharField(default='', max_length=255, verbose_name='City of Residence')),
                ('country', models.CharField(default='', max_length=255, verbose_name='Country of Residence')),
                ('office', models.CharField(default='', max_length=255, verbose_name='Organization you are working for/studying at')),
                ('job_title', models.CharField(default='', max_length=255, verbose_name='Position/Major')),
                ('message', models.CharField(default='', max_length=1000, verbose_name='Message to VGU Alumni Community')),
            ],
        ),
    ]
