# Generated by Django 2.0.3 on 2018-05-19 14:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, validators=[core.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
