# Generated by Django 2.0.3 on 2018-04-04 14:12

from django.db import migrations, models
import django.db.models.deletion
from job.models import JobField

def populate_fields(apps, *_):
    field_datas = [
        ('Accounting/Auditing', 'https://i.imgur.com/HGjPTY5.jpg'),
        ('Arts/Design', 'https://i.imgur.com/6ubLauf.jpg'),
        ('Banking/Consulting', 'https://i.imgur.com/D1yvkAk.jpg'),
        ('Civil/Construction', 'https://i.imgur.com/rYyojcd.jpg'),
        ('Finance', 'https://i.imgur.com/e9mdaVR.jpg'),
        ('Electrical/Electrics', 'https://i.imgur.com/EU7YTws.jpg'),
        ('Human Resources', 'https://i.imgur.com/IwDNlvm.jpg'),
        ('IT', 'https://i.imgur.com/d1Zta0M.jpg'),
        ('Logistics/Suply Chain', 'https://i.imgur.com/r1z4V7t.jpg'),
        ('Marketing', 'https://i.imgur.com/xckJ4D3.jpg'),
        ('Sales', 'https://i.imgur.com/h2LHBgs.jpg'),
    ]

    for name, url in field_datas:
        field = JobField.objects.create(name=name, file_img_url=url)
        field.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Field')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Job Description')),
                ('requirement', models.TextField(blank=True, max_length=255, null=True, verbose_name='Job Requirement')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salary')),
                ('benefit', models.TextField(blank=True, max_length=255, null=True, verbose_name='Benefits')),
                ('apply_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resume Application To')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('question_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='For More Information')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Posted')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Post scheduled time')),
                ('facebook_post_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Post ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Field Name')),
                ('slug', models.SlugField()),
                ('file_img_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field', to='job.JobField', verbose_name='Job Field'),
        ),
        migrations.RunPython(populate_fields)
        ,
    ]
